In [2]:
import numpy as np
# generate random numbers in a 5x5 array
random = np.random.random((5,5))
# set the random array to variable X
X = random
# perform the formula: Z = (X - mean) / standev
Z = (X - np.mean(X)) / np.std(X)
# output
print(Z)
# save as .npy 
np.save('X_normalized', Z)

[[-0.18548914  0.68345288 -0.4983628   0.22185654 -0.25994831]
 [ 0.86004558 -1.22130247 -1.14165313 -1.44095775 -1.4835433 ]
 [ 1.57736008 -1.35022213  0.24998546 -0.31058365 -0.59979231]
 [ 1.39083225 -0.53561891  1.38890792  1.56298723  1.57628824]
 [-0.30166309 -0.44915232  0.59273879  0.76328536 -1.08945102]]


In [4]:
import numpy as np
# create a 10x10 matrix with the squares of the number and use the arange function to limit it from 1 to 100
numbers = np.arange(1,101)
squared = numbers**2
# use reshape to make it into a 10x10 table
table = squared.reshape(10,10)
# print the table
print(table)

# use modulo to separate the numbers that are divisible by 3
three = table[table % 3 == 0]
print(" ")
# print
print("Numbers divisible by 3")
print(" ")
print(three)
# save as .npy
np.save("div_by_3", three)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
 
Numbers divisible by 3
 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [14]:
# test if the file will load
import numpy as np
load = np.load('X_normalized.npy')
load

array([[-0.18548914,  0.68345288, -0.4983628 ,  0.22185654, -0.25994831],
       [ 0.86004558, -1.22130247, -1.14165313, -1.44095775, -1.4835433 ],
       [ 1.57736008, -1.35022213,  0.24998546, -0.31058365, -0.59979231],
       [ 1.39083225, -0.53561891,  1.38890792,  1.56298723,  1.57628824],
       [-0.30166309, -0.44915232,  0.59273879,  0.76328536, -1.08945102]])

In [12]:
# test if the file will load
import numpy as np
load = np.load('div_by_3.npy')
load

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])